use_frameworks!

platform :ios, '9.0'

target 'HYLearningSwift_Example' do
  pod 'HYLearningSwift', :path => '../'

  target 'HYLearningSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
